### ISSUE TITLE
skill_xp_multiplier does not seem to work with aurelium skills

### ISSUE THREAD

**Issue by Blazenfury2314** [Auxilor/EcoArmor#10]
When using skill_xp_multiplier while having aurelium skills installed as a skills plugin this error pops in the console:

24.02 14:24:40 [Server] WARN Invalid configuration for skill_xp_multiplier in context Armor Set farmer:
24.02 14:24:40 [Server] WARN (Cause) Argument 'id'
24.02 14:24:40 [Server] WARN (Reason) Invalid effect ID specified!
24.02 14:24:40 [Server] WARN Invalid configuration for skill_xp_multiplier in context Armor Set farmer (Advanced):

the discord told me that this should be part of the function of skills_xp_multiplier, if this is not an intended function and this is only supposed to work with ecoskills please disregard and I apologize for taking up your time.

1. Install aurelium skills, eco and ecoarmor
2. add the "id: skill_xp_multiplier" to a list of effect on an armor set
3. reload ecoarmor

**Expected behavior**
No error should appear and and the armor should have the intended effect based on the number following the id

**Server Information (please complete the following information):**
- Version: Purpur version git-Purpur-1506 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 84028e2 on HEAD)
- Version of Eco: 6.26.3
- Version of EcoArmor: 7.35.0

**Comment by WillFP** [comment]
AureliumSkills doesn't support skill multipliers, so I can't add support for that. Use EcoSkills instead!
