### ISSUE TITLE
infinite health glitch

### ISSUE THREAD

**Issue by iSeitan** [Auxilor/EcoArmor#18]
Player can take damage, then remove armor and re equip it to gain full health again and again and again
https://youtu.be/9eH9J16-7ww
https://youtu.be/nk5gJEdpUYQ

please fix as this this game breaking :)

**Comment by iSeitan** [comment]
Huge issue, would be nice to find how to fix :D

**Comment by iSeitan** [comment]
Still an issue

**Comment by iSeitan** [comment]
Still an issue and player can abuse it without any trace in logs

**Comment by WillFP** [comment]
ok 2 secs lemme fix this

**Comment by ltjessem** [comment]
It this fixed?
