### ISSUE TITLE
Player Heads as helmets broken. (No Lore/Shards do not work)

### ISSUE THREAD

**Issue by hungovermc** [Auxilor/EcoArmor#24]
**Describe the bug**
When using a player head as a helmet, the item doesn't show lore and also cannot have shards applied to it.

**To Reproduce**
1. Create a helmet with a Player Head as the item.
2. Go in-game after reloading plugin
3. Head does not have lore/shards do not work

**Expected behavior**
What should happen is the helmet should have lore like the rest of the armor and the shards should upgrade its tier like usual.

![2022-05-20_16 11 29](https://user-images.githubusercontent.com/104597647/169558856-869a08e1-28f9-4d54-96a5-d7afab43cb2d.png)
![helmetbug](https://user-images.githubusercontent.com/104597647/169559039-79bfbefd-342c-4caa-83c5-b245cf6ae309.gif)

**Server Information (please complete the following information):**
- Version: This server is running Paper version git-Paper-"e7d928a" (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)
- Eco armor Ver: 7.53.0
- Eco Ver: 6.35.2

**Comment by WillFP** [comment]
Due to inventory limitations, crystals/shards only work in survival
