### ISSUE TITLE
Lore shows %tier% 

### ISSUE THREAD

**Issue by OmegaWulf** [Auxilor/EcoArmor#31]
**Describe the bug**
Lore shows %tier% sometimes 

**To Reproduce**
1. Hover over EcoArmor item in inventory
2. Lore shows all values correctly except tier shows up as: `%tier%`

**Expected behavior**
I expect to the see the value of %tier% and not the actual text `%tier% 

**Screenshots**
![Screen Shot 2022-06-17 at 2 48 35 PM](https://user-images.githubusercontent.com/42750678/176726337-b8e63a15-7595-4fd8-940e-7b86ab4bfc03.png)

**Server Information (please complete the following information):**
- Paper 1.18.2
- Latest eco versions 

**Additional context**
Click on/off item will usually fix it.

**Comment by WillFP** [comment]
Fixed!
