### ISSUE TITLE
Enchantments do not display in armor lore.

### ISSUE THREAD

**Issue by PQguanfang** [Auxilor/EcoArmor#32]
**Describe the bug**
Any enchantments do not display in armor lore.

**To Reproduce**
1. Try enchant the armors in enchantment table.
2. Enchant successfully, but the enchantments do not display in armor lore.

**Expected behavior**
The lore should display armor lore.

**Screenshots**
<img width="342" alt="屏幕截图 2022-07-03 214303" src="https://user-images.githubusercontent.com/35395058/177042517-75064252-adda-456e-bbc8-f0db41ca44af.png">

**Server Information (please complete the following information):**
- Version: This server is running Pufferfish version git-Pufferfish-5 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: fdfb106 on HEAD)
You are running 5 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
- Version of plugin and eco: 7.87.2 and 6.37.1

**Additional information**
Problem get solved after try downgrade EcoArmor to 7.87.0.

**Comment by WillFP** [comment]
Fixed!
