### ISSUE TITLE
In_water and is_night conditions trigger incorrectly

### ISSUE THREAD

**Issue by Tombspyder** [Auxilor/EcoArmor#4]
**Describe the bug**
The In_water and is_night condition both do not function as intended, only working if the set is equipped when the condition is met and not giving the effect if the condition is met whilst wearing

**To Reproduce**
1. Create an Armor set using either condition
2. Equip Armor set whilst condition is NOT met
3. Attempt to meet condition
4. Result

**Expected behavior**
Conditions should work as intended and update when the condition is met

**Screenshots**
https://user-images.githubusercontent.com/88732543/151160432-69733608-0eca-40b9-853a-37ce9fc6c8ce.mp4

**Server Information (please complete the following information):**
- Version: This server is running Paper version git-Paper-140 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: d9fb602)
You are 36 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-133 (MC: 1.18.1)

- Version of plugin and eco: Eco 6.20.4; EcoArmor: 7.22.3

**Additional context**
N/A

**Comment by WillFP** [comment]
Fixed in latest
