### ISSUE TITLE
hunger_multiplier/food_multiplier not functioning correctly

### ISSUE THREAD

**Issue by btjt97** [Auxilor/EcoArmor#5]
**Describe the bug**
Migrating two reports: hunger_multiplier/food_multiplier not functioning, add or remove support.

**Screenshots**
![image](https://user-images.githubusercontent.com/98480009/151212312-8e9d2be5-3d40-4e4c-a8a7-863e16119c75.png)
![image](https://user-images.githubusercontent.com/98480009/151212555-a6a7b23b-ad9d-447b-82fc-e19c8745ff07.png)

**Server Information (please complete the following information):**
- Version: latest

**Additional context**
Migrated two open reports of hunger_multiplier/food_multiplier not working, limited info

**Comment by WillFP** [comment]
Fixed in latest
