### ISSUE TITLE
Permanent Potion effect are lost when dieing with keepinventory

### ISSUE THREAD

**Issue by Uharn** [Auxilor/EcoArmor#6]
If you use a permanent potion effect on an armor, the potion effect is lost after you die when you have keep inventory
you have to desequipp/reequip the armor to get it back

**Comment by Uharn** [comment]
We tried to cheat it using a static potion effect every X ticks, but then we get tha annoying potion effect particles

**Comment by WillFP** [comment]
Fixed in latest
