### ISSUE TITLE
Potion effect gets cleared on TP/world change from armor sets

### ISSUE THREAD

**Issue by iSeitan** [Auxilor/EcoArmor#9]
**Describe the bug**
When a player gets TP, TP or change world the armor sets that gives potion effect get cleared and th eplayer must unequip and re equip so the effect works again and its a pain to be honest

**To Reproduce**
1. wear an armor sets that give a potion effect
2. use the potion effect
3. tp or change world
4. try to use the potion effect and see that it doesnt work anymore

**Expected behavior**
That the potion effect works all the time when wearing the eco armor

**Comment by WillFP** [comment]
Fix coming in next version
